name: Build test page to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      tags:
        description: 'Run workflow manually'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Setup Pages
        uses: actions/configure-pages@v2
      
      - name: Build vite
        run: |
          npm install
          npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
    
      - name: Prepare Build Output
        run: |
          ls | grep -v  dist | awk  '{system("rm -rf "$1)}' 
          # 将dist文件夹内容移动到根目录
          mv dist/* .
          # 清理残留文件
          rm -rf dist
          rm .gitignore
          # 确保存在提交内容
          touch .keep

      - name: Deploy to Dist Branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # 添加所有文件到暂存区
          git add -A
          
          # 尝试提交（忽略空提交错误）
          git commit -m "Deploy from main (${GITHUB_SHA:0:7})" || echo "No changes to commit"
          
          # 强制推送到dist分支
          git push origin HEAD:dist --force